### ISSUE TITLE
usability enhancements for all optional inputs

### ISSUE THREAD

**Issue by kggilmer** [awslabs/smithy-kotlin#129]
#176446022 normalized operation inputs/outputs.

This task would be to look into improving usability of operations where we generate a synthetic input with all optional fields such that we could go from:
```
suspend fun foo(input: FooRequest): FooResponse
```

to either:
```
suspend fun foo(input: FooRequest? = null): FooResponse

OR

suspend fun foo(input: FooRequest = FooRequest{}): FooResponse
```

which would allow customers to call it as:
```
client.foo() // instead of client.foo(FooRequest{})
```

We need to understand how safe this actually is and if there are any "gotchas". Would we do this for all requests that have all optional fields? Is it _really_ guaranteed that a service team never adds `@required` somewhere down the road?

see also QUIP: 7C7jARMeOD6H/AWS-Kotlin-SDK-Service-Client-Design#AMY9CAN4eab

*internal id*: 177192194

**Comment by lucix-aws** [comment]
We discussed this in our standup today.

Regarding the question originally posed by Ken-
> Is it really guaranteed that a service team never adds @required somewhere down the road?

It is our understanding that this will NOT be done, except in cases where a request parameter was defacto required at the service level, but incorrectly not marked as such in the IDL. Doing otherwise would break literally everyone using the service, not just our SDK.

We can implement this without breaking our own backwards compatibility by implementing default arguments for appropriate methods as described above
```kotlin
suspend fun foo(input: FooRequest = FooRequest{}): FooResponse
```

I would clarify that the condition for doing this isn't exactly "all optional fields", rather it is "no required fields" - the latter is more inclusive to cover the case where a method is explicitly defined to take no parameters
