### ISSUE TITLE
How is this project used?

### ISSUE THREAD

**Issue by mwalkerr** [awslabs/smithy-kotlin#717]
We have Smithy models setup and are doing some Typescript generation. How can `smithy-kotlin-codegen` be used to generate Kotlin types from the model?

**Comment by aajtodd** [comment]
What are you trying to do? Generate a client for a service model? Just generate types for shapes? Would love to hear more about your use case. 

This project is in active development and is right now primarily used to generate code for the [AWS SDK for Kotlin](https://github.com/awslabs/aws-sdk-kotlin). Other use cases and generic Smithy codegen of non AWS models is certainly the aim of this project but there may be missing pieces depending on what your goal is.

There are some [instructions](https://github.com/awslabs/aws-sdk-kotlin/blob/main/docs/howto/client-generator.md) in the SDK repo that could serve as a getting started for how to go from model to generated code. You'll need to replace the dependency with [smithy-kotlin-codegen](https://search.maven.org/artifact/software.amazon.smithy.kotlin/smithy-kotlin-codegen) instead of the AWS specific generator referenced in the linked guide). All of the `smithy-*` code generators are built on the same underlying technology and work the same (as far as codegen machinery is concerned). If you have Typescript generation working it should be relatively the same process.

**Comment by mwalkerr** [comment]
Hey @aajtodd thanks for the quick response and apologies for not including more info. Yes, just trying to generate Kotlin types for the shapes currently. 

Let me check out the instructions from the link you sent
