### ISSUE TITLE
Expected HTTP status code from model is not respected

### ISSUE THREAD

**Issue by aajtodd** [awslabs/smithy-kotlin#836]
## Describe the bug

Operations with the [HTTP trait](https://smithy.io/2.0/spec/http-bindings.html#http-trait) are generated with an [expected](https://github.com/awslabs/smithy-kotlin/blob/e8fe25b768ba0eb5253635692ab7d91cec26b35f/runtime/protocol/http-client/common/src/aws/smithy/kotlin/runtime/http/operation/HttpOperationContext.kt#L75) HTTP status

```kotlin
    override suspend fun getCallerIdentity(input: GetCallerIdentityRequest): GetCallerIdentityResponse {
        val op = SdkHttpOperation.build<GetCallerIdentityRequest, GetCallerIdentityResponse> {
            serializer = GetCallerIdentityOperationSerializer()
            deserializer = GetCallerIdentityOperationDeserializer()
            context {
                expectedHttpStatus = 200       <----------- from model
                operationName = "GetCallerIdentity"
            }
            execution.auth = OperationAuthConfig(AuthSchemeProviderAdapter, configuredAuthSchemes, identityProviderConfig)
            execution.retryStrategy = config.retryStrategy
        }
        ...
}
```

## Expected Behavior

If an expected status is set for the operation it should be favored instead of assuming 2xx is correct.

## Current Behavior

Operation deserializers are generated using the `isSuccess` extension which just looks for 2xx code.

```kotlin
internal class GetCallerIdentityOperationDeserializer: HttpDeserialize<GetCallerIdentityResponse> {

    override suspend fun deserialize(context: ExecutionContext, response: HttpResponse): GetCallerIdentityResponse {
        if (!response.status.isSuccess()) {
            throwGetCallerIdentityError(context, response)
        }
        val builder = GetCallerIdentityResponse.Builder()

        val payload = response.body.readAll()
        if (payload != null) {
            deserializeGetCallerIdentityOperationBody(builder, payload)
        }
        return builder.build()
    }
}
```

## Your Environment

* Smithy Kotlin version used: 0.17.1
* Platform (JVM/JS/Native): All
* Operating System and version: All

**Comment by lauzadis** [comment]
After implementing this, we noticed some protocol tests started failing because they [don't model](https://github.com/awslabs/smithy/blob/main/smithy-aws-protocol-tests/model/restJson1/http-response-code.smithy#L12) an expected response code (defaults to 200) but the tests [expect a response of 201](https://github.com/awslabs/smithy/blob/main/smithy-aws-protocol-tests/model/restJson1/http-response-code.smithy#L45-L63).

We also noticed that Smithy's validators [don't allow modeled codes outside of the 2xx range](https://github.com/awslabs/smithy/blob/c619a9a4a16f8cffbf4adcc06d32ecbe73ade669/smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/HttpResponseCodeSemanticsValidator.java#L55-L57) while the spec says all codes between 100 and 999 are allowed. 

Pausing work on this until we get clarity about these two issues from the Smithy team.

**Comment by lauzadis** [comment]
We've decided not to complete this issue. Smithy recommends users to model codes within the 2xx range and throws a `danger` level warning if a modeled code deviates from this range. The SDK already validates all 2xx codes and won't gain any new functionality by adding support for these modeled codes.
